### ISSUE TITLE
keccak256 tests failing

### ISSUE THREAD

**Issue by tohrnii** [maticnetwork/miden#224]
Maybe this is a known temporary issue in keccak256 assembly procedure since the tests were ignored but tests `keccak256_2_to_1_hash` and `keccak256_bit_interleaving` are failing.

Error Message:
```
---- stdlib::crypto::keccak256::keccak256_2_to_1_hash stdout ----
thread 'stdlib::crypto::keccak256::keccak256_2_to_1_hash' panicked at 'Failed to compile test source.: assembly error at 709: dangling instructions after module end at std::crypto::hashes::keccak256', miden/tests/integration/helpers.rs:134:14

---- stdlib::crypto::keccak256::keccak256_bit_interleaving stdout ----
thread 'stdlib::crypto::keccak256::keccak256_bit_interleaving' panicked at 'Failed to compile test source.: assembly error at 709: dangling instructions after module end at std::crypto::hashes::keccak256', miden/tests/integration/helpers.rs:134:14
```

**Comment by tohrnii** [comment]
Closed by #227
