### ISSUE TITLE
Error in building auxiliary column trace

### ISSUE THREAD

**Issue by 0xKanekiKen** [maticnetwork/miden#386]
I was writing out an integration test for `INV` stack operation when I stumbled across the error on running the following:
 
```
#[test]
fn inv() {
    // Test on random input state and operation. 
    let asm_op = "inv push.10 inv";
    let pub_inputs = vec![1];

    build_op_test!(&asm_op, &pub_inputs).prove_and_verify(pub_inputs, 1, false);
}
```

```
running 1 test
thread 'air::stack::field_ops::inv' panicked at 'assertion failed: `(left == right)`
  left: `QuadExtension(BaseElement(3647271249661219449), BaseElement(6130618514712835224))`,
 right: `QuadExtension(BaseElement(1), BaseElement(0))`', /home/admin/Desktop/Polygon/miden/processor/src/trace/utils.rs:188:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
   2: core::panicking::assert_failed_inner
   3: core::panicking::assert_failed
             at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:181:5
   4: miden_processor::trace::utils::AuxColumnBuilder::build_aux_column
             at /x/xx/xxx/xxxx/miden/processor/src/trace/utils.rs:188:9
   5: miden_processor::stack::aux_trace::AuxTraceBuilder::build_aux_columns
             at /x/xx/xxx/xxxx/miden/processor/src/stack/aux_trace.rs:24:18
   6: <miden_processor::trace::ExecutionTrace as winter_prover::trace::Trace>::build_aux_segment
             at /x/xx/xxx/xxxx/miden/processor/src/trace/mod.rs:198:33
```

**Comment by grjte** [comment]
@0xKanekiKen This seems to be passing now when I test it.

**Comment by 0xKanekiKen** [comment]
Thanks, @grjte for investigating it.
